version: '3'

services:
  main:
    depends_on:
      - db
    build: .
    image: education-lrs
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: |
      bash -c '
        echo "Running tests..."
        npm install
        npm run migrate:test
        if [ "${IS_CI}" = "" ]
        then
          npm test
        else
          npm run test-ci
        fi
      '
    volumes:
      - ./:/app
  db:
    image: postgres:14
    container_name: integration-tests-prisma
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      postgres_DB: tests
